apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastfood-pedido-hpa
  namespace: fastfood
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastfood-pedido-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
